name: release

on:
  release:
    types: [published]

jobs:
  build-windows:
    defaults:
      run:
        working-directory: .\\build
    strategy:
      fail-fast: false
      matrix:
        name:
          - windows_x86_64
          # - windows_arm64
          # - windows_x86
    runs-on: windows-2022
    outputs:
      output-artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
    - uses: actions/checkout@v4
    - name: Determine Release Tag
      env:
        RELEASE: ${{ github.ref_name }}
      id: release_tag
      run: |
        $tag = $Env:RELEASE.split(".")[0]
        echo "tag=$tag" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "3P_WEBRTC_BUILD_RELEASE_VERSION=$Env:RELEASE" | Out-File -FilePath .\\VERSION -Encoding utf8 -Append
    - name: Disk Cleanup
      run: |
        Get-PSDrive
        # Cache 済み Docker Image の削除
        # Clean unused docker images
        docker rmi $(docker images -q -a)
        # Android SDK の削除
        # Delete Android SDK
        Remove-Item -Recurse -Force $Env:ANDROID_HOME -ErrorAction Ignore
        Remove-Item -Recurse -Force $Env:ANDROID_NDK_HOME -ErrorAction Ignore
        # JVM の削除
        # Delete JVM
        Remove-Item -Recurse -Force $Env:JAVA_HOME_11_X64 -ErrorAction Ignore
        Remove-Item -Recurse -Force $Env:JAVA_HOME_8_X64 -ErrorAction Ignore
        Get-PSDrive
    - run: "& .\\build.${{ matrix.name }}.ps1 \"${{ steps.release_tag.outputs.tag }}_release\""
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: webrtc.${{ matrix.name }}
        path: build\_package\${{ matrix.name }}\webrtc.tar.bz2
  build-macos:
    defaults:
      run:
        working-directory: ./build
    strategy:
      fail-fast: false
      matrix:
        name:
          - macos_arm64
          - macos_x86_64
          # - ios
    runs-on: macos-15
    outputs:
      output-artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 16.0
      run: sudo xcode-select --switch /Applications/Xcode_16.0.app/Contents/Developer
    - run: brew install ninja
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install setuptools
    - name: Determine Release Tag
      env:
        RELEASE: ${{ github.ref_name }}
      id: release_tag
      run: |
        echo "tag=${RELEASE%%.*}" >> "$GITHUB_OUTPUT"
        echo "3P_WEBRTC_BUILD_RELEASE_VERSION=${RELEASE}" >> "VERSION"
    - run: ./build.${{ matrix.name }}.sh "${{ steps.release_tag.outputs.tag }}_release"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: webrtc.${{ matrix.name }}
        path: build/_package/${{ matrix.name }}/webrtc.tar.bz2
  build-linux:
    defaults:
      run:
        working-directory: ./build
    strategy:
      fail-fast: false
      matrix:
        name:
          # - raspberry-pi-os_armv6
          # - raspberry-pi-os_armv7
          # - raspberry-pi-os_armv8
          # - ubuntu-18.04_armv8
          # - ubuntu-20.04_armv8
          # - ubuntu-18.04_x86_64
          - ubuntu-20.04_x86_64
          # - ubuntu-22.04_x86_64
          # - android
    runs-on: linux-large 
    outputs:
      output-artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
    - uses: actions/checkout@v4
    - name: Disk Cleanup
      run: |
        df -h
        docker container prune -f
        docker image prune -a -f
        # 3.9GB
        sudo rm -rf /usr/local/share/boost
        # 17GB
        sudo rm -rf /usr/share/dotnet
        df -h
    - name: Determine Release Tag
      env:
        RELEASE: ${{ github.ref_name }}
      id: release_tag
      run: |
        echo "tag=${RELEASE%%.*}" >> "$GITHUB_OUTPUT"
        echo "3P_WEBRTC_BUILD_RELEASE_VERSION=${RELEASE}" >> "VERSION"
    - run: ./build.${{ matrix.name }}.sh "${{ steps.release_tag.outputs.tag }}_release"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: webrtc.${{ matrix.name }}
        path: build/_package/${{ matrix.name }}/webrtc.tar.bz2
  package-macos:
    needs:
    - build-macos
    runs-on: macos-15
    steps:
    # Checkout first to avoid damaging artifact download below
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Work around the fact that in the context of a pull request github.sha
        # references a dynamic merge commit rather than the branch head
        # https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        fetch-depth: 0
        submodules: recursive
    - name: Download webrtc artifacts
      uses: actions/download-artifact@v4
      with:
        path: _packages
    - uses: secondlife/action-autobuild@v5
      with:
        checkout: false
        token: ${{ github.token }}
        build-args: ../build-cmd.sh ${{ needs.build-macos.outputs.output-artifact-id }}
  package-windows:
    needs:
    - build-windows
    runs-on: windows-2022
    steps:
    # Checkout first to avoid damaging artifact download below
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Work around the fact that in the context of a pull request github.sha
        # references a dynamic merge commit rather than the branch head
        # https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        fetch-depth: 0
        submodules: recursive
    - name: Download webrtc artifacts
      uses: actions/download-artifact@v4
      with:
        path: _packages
    - uses: secondlife/action-autobuild@v5
      with:
        checkout: false
        token: ${{ github.token }}
        build-args: ../build-cmd.sh ${{ needs.build-windows.outputs.output-artifact-id }}
  package-linux:
    needs:
    - build-linux
    runs-on: ubuntu-latest
    steps:
    # Checkout first to avoid damaging artifact download below
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Work around the fact that in the context of a pull request github.sha
        # references a dynamic merge commit rather than the branch head
        # https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        fetch-depth: 0
        submodules: recursive
    - name: Download webrtc artifacts
      uses: actions/download-artifact@v4
      with:
        path: _packages
    - uses: secondlife/action-autobuild@v5
      with:
        checkout: false
        token: ${{ github.token }}
        build-args: ../build-cmd.sh ${{ needs.build-linux.outputs.output-artifact-id }}
  release:
    needs:
    - package-windows
    - package-macos
    - package-linux
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/m')
    steps:
      - uses: secondlife/action-autobuild-release@v3
